name: Discourse compatibility branch
on:
  push:
    branches:
      - d-compat/**
  pull_request:
    branches:
      - d-compat/**
  workflow_dispatch:

jobs:
  discourse-branch:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{steps.determine.outputs.branch}}
    steps:
    - id: determine
      run: |
        USE_REF=${GITHUB_BASE_REF:-$GITHUB_REF}
        DISCOURSE_BRANCH=release/${USE_REF#*/d-compat/}
        echo "Use discourse branch: $DISCOURSE_BRANCH"
        echo "branch=$DISCOURSE_BRANCH" >> "$GITHUB_OUTPUT"
  ci:
    needs: discourse-branch
    uses: discourse/.github/.github/workflows/discourse-plugin.yml@v1
    with:
      core_ref: ${{needs.discourse-branch.outputs.branch}}
