name: Discourse tests-passed
on:
  #push:
  #  branches:
  #    - main
  #pull_request:
  workflow_dispatch:

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "This would test the plugin/theme against the tests-passed branch"
  #ci:
  #  uses: discourse/.github/.github/workflows/discourse-plugin.yml@v1
  #  with:
  #    core_ref: tests-passed
